FROM registry.access.redhat.com/ubi8/ubi-minimal:8.1
WORKDIR /work/

RUN microdnf install gcc && microdnf clean all

# set up permissions for user `1001`
RUN chmod 775 /work \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

VOLUME /work/src/
VOLUME /work/bin/

ENTRYPOINT ["g++", "-Wall", "-O2", "-o", "./bin/main", "-lm", "-pthread", "-fomit-frame-pointer"]