FROM registry.access.redhat.com/ubi8/ubi-minimal:8.1
WORKDIR /work/

# set up permissions for user `1001`
RUN chmod 775 /work \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

RUN microdnf install java-11-openjdk-devel && microdnf clean all
